In [2]:
import os
os.chdir('../..')
os.getcwd()

'/Users/liamsaliba/projects/comp90054-yinsh-project-group-42'

In [10]:
import numpy as np

In [4]:
from Yinsh.yinsh_model import YinshState as State

In [6]:
state = State(2)

In [18]:
n_legal = np.sum(state.board == 0)
n_legal

85

In [34]:
board = np.array([
       [5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 5],
       [5, 5, 5, 5, 2, 0, 0, 2, 0, 0, 0],
       [5, 5, 5, 0, 0, 2, 2, 2, 0, 0, 0],
       [5, 5, 0, 0, 0, 2, 2, 4, 0, 0, 0],
       [5, 0, 0, 4, 4, 2, 4, 4, 0, 0, 0],
       [5, 0, 0, 0, 2, 2, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5],
       [5, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5]]
)

In [81]:
x, y = 2,5
s = x + y
pos = [(x+i, y-i) for i in range(-10, 11) 
                    if (0 <= x+i <= 10 and 0 <= y-i <= 10) ]
pos

[(0, 7), (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1), (7, 0)]

In [111]:
np.fliplr(board)[:, :, None].diagonal()

array([[5, 0, 0, 4, 4, 2, 0, 0, 0, 0, 5]])

In [113]:
[np.fliplr(board).diagonal(s) for s in range(-5, 5)]

[array([5, 0, 0, 0, 0, 5]),
 array([0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 4, 0, 2, 0, 0, 0, 0]),
 array([5, 0, 0, 4, 4, 2, 0, 0, 0, 0, 5]),
 array([0, 0, 2, 2, 2, 2, 0, 0, 0, 0]),
 array([0, 2, 2, 2, 4, 0, 0, 0, 0]),
 array([0, 0, 2, 0, 4, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0])]

In [102]:
np.diag(board[:, ::-1], 10-5)

array([5, 2, 0, 0, 0, 5])

In [83]:
board[tuple(zip(*pos))] == np.diag(board[:, ::-1], 10-(x+y))

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [85]:
def getline(line, pos):
    x, y = pos
    if line == 'h':
        return board[x, :]
    elif line == 'v':
        return board[:, y]
    else:
        return np.diag(board[:, ::-1], 10-(x+y))

In [95]:
getline('v', (2,5))

array([5, 0, 2, 2, 2, 2, 2, 0, 0, 0, 5])

In [47]:
# return a 1D array of all elements of board on the diagonal of (x, y)
board[x::-1, y::-1]

array([[2, 2, 0, 0, 0, 5],
       [2, 4, 4, 0, 0, 5],
       [2, 0, 0, 0, 5, 5],
       [2, 0, 0, 5, 5, 5],
       [0, 2, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [44]:
(board == 2).nonzero()

(array([1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 6]),
 array([4, 7, 5, 6, 7, 5, 6, 5, 4, 5, 5]))

In [35]:
board[0]

array([5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 5])

In [29]:
5 ** 61

4336808689942017736029811203479766845703125

In [21]:
possible_initial_states = 1
for i in range(10):
    possible_initial_states *= n_legal - i
possible_initial_states

/var/folders/4h/h790lrsn7cb2n7k080lvzqtc0000gn/T/ipykernel_13036/2091988017.py:3: RuntimeWarning: overflow encountered in long_scalars
  possible_initial_states *= n_legal - i


-7091638567248034816

In [ ]:
def checkLineNP(sequences, )